import { INCIDENTS, KB_SERVICES, CHANGE_REQUESTS, KB_ENTRIES } from "./mock-data";

export type AnalyzeResponse = {
  found: boolean;
  markdown: string;
  changes: {
    number: string;
    title: string;
    deployed_at: string;
    owner: string;
    risk: "Low" | "Medium" | "High";
  }[];
};

export function fetchIncident(number: string) {
  const n = number.trim().toUpperCase();
  return INCIDENTS.find((i) => i.number.toUpperCase() === n) ?? null;
}

export function analyzeIncident(input: {
  number: string;
  context: string;
  logs: string;
  service: string;
}): AnalyzeResponse {
  const svc = input.service.trim().toLowerCase();
  const kb = KB_SERVICES[svc];
  const changes = CHANGE_REQUESTS[svc] ?? [];

  if (!kb) {
    return {
      found: false,
      markdown: "",
      changes,
    };
  }

  const md = `# Proposed Solution — ${input.number || "(no ticket)"}

**Service:** \`${svc}\`
**Generated:** ${new Date().toISOString()}

## Summary
${kb.summary}

## Likely Root Cause
Based on the provided context and log signals, the most likely root cause is a
downstream dependency degradation affecting \`${svc}\`. Correlated signals:

- Elevated error rate on primary endpoints
- Retry storms visible in logs
- Recent change activity within the last 7 days (see below)

## Log Highlights
\`\`\`
${input.logs.split("\n").slice(0, 6).join("\n")}
\`\`\`

## Recommended Runbook
${kb.runbook
  .split("\n")
  .map((l) => (l.trim().match(/^\d+\./) ? l : `- ${l}`))
  .join("\n")}

## Next Steps
1. Execute the runbook above in a war-room session.
2. Correlate with recent change requests (listed in the UI).
3. If the incident persists after 30 minutes, escalate to the service owner.

---
*Generated by Ops Console*
`;

  return { found: true, markdown: md, changes };
}

export function getKbEntries() {
  return KB_ENTRIES;
}

export function jsonKbToMarkdown(entry: (typeof KB_ENTRIES)[number]) {
  const parts: string[] = [];
  parts.push(`# ${entry.service}`);
  parts.push("");
  parts.push(`**Git Repo:** ${entry.git_repo}  `);
  parts.push(`**Config Repo:** ${entry.config_repo}  `);
  parts.push(`**Updated:** ${entry.updated_at}`);
  parts.push("");
  for (const [heading, body] of Object.entries(entry.sections)) {
    parts.push(`## ${heading}`);
    parts.push(body);
    parts.push("");
  }
  return parts.join("\n");
}

export function generateKbMarkdown(input: {
  service: string;
  git_repo: string;
  config_repo: string;
}) {
  const now = new Date().toISOString();
  return {
    service: input.service,
    git_repo: input.git_repo,
    config_repo: input.config_repo,
    updated_at: now,
    markdown: `# ${input.service}

**Git Repo:** ${input.git_repo}  
**Config Repo:** ${input.config_repo}  
**Generated:** ${now}

## Overview
Auto-generated knowledge base entry for \`${input.service}\`. Populate this
section with architecture notes as the service evolves.

## Dependencies
_Discovered from repository manifests. Edit as needed._

## Common Failures
- Deployment regressions
- Downstream dependency outages
- Configuration drift between environments

## Runbook
1. Check recent deploys and change requests
2. Inspect service dashboards and error rate
3. Roll back the latest change if impact is customer-facing

## Contacts
Service owners — update this section with pager and Slack channel.
`,
  };
}
