/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as DocFactoryRouteImport } from './routes/doc-factory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKbRouteImport } from './routes/api/kb'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const DocFactoryRoute = DocFactoryRouteImport.update({
  id: '/doc-factory',
  path: '/doc-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbRoute = ApiKbRouteImport.update({
  id: '/api/kb',
  path: '/api/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doc-factory': typeof DocFactoryRoute
  '/triage': typeof TriageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/kb': typeof ApiKbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doc-factory': typeof DocFactoryRoute
  '/triage': typeof TriageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/kb': typeof ApiKbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doc-factory': typeof DocFactoryRoute
  '/triage': typeof TriageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/kb': typeof ApiKbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doc-factory'
    | '/triage'
    | '/api/analyze'
    | '/api/incidents'
    | '/api/kb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doc-factory'
    | '/triage'
    | '/api/analyze'
    | '/api/incidents'
    | '/api/kb'
  id:
    | '__root__'
    | '/'
    | '/doc-factory'
    | '/triage'
    | '/api/analyze'
    | '/api/incidents'
    | '/api/kb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocFactoryRoute: typeof DocFactoryRoute
  TriageRoute: typeof TriageRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
  ApiKbRoute: typeof ApiKbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-factory': {
      id: '/doc-factory'
      path: '/doc-factory'
      fullPath: '/doc-factory'
      preLoaderRoute: typeof DocFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb': {
      id: '/api/kb'
      path: '/api/kb'
      fullPath: '/api/kb'
      preLoaderRoute: typeof ApiKbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocFactoryRoute: DocFactoryRoute,
  TriageRoute: TriageRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
  ApiKbRoute: ApiKbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
